#!/bin/bash

export FZF_DEFAULT_OPTS="
  --color=bg+:#1e2a44,bg:#000000,spinner:#89b4fa,hl:#89b4fa
  --color=fg:#cdd6f4,header:#89b4fa,info:#cdd6f4,pointer:#89b4fa
  --color=marker:#89b4fa,fg+:#ffffff,prompt:#89b4fa,hl+:#89b4fa
  --color=border:#40507a,preview-border:#89b4fa
  --border=none
  --margin=0,0
  --padding=1,3
  --layout=reverse
  --info=inline-right
  --pointer='⟨⟩'
  --marker='⟨⟩'
"

# Menggunakan eval agar tilde (~) terbaca sebagai home directory secara absolut
CONFIG_DIR=$(eval echo ~/.config)

fd -E "**.sixel" --base-directory "$CONFIG_DIR" --type f | \
  fzf --preview "/data/data/com.termux/files/usr/bin/bat $CONFIG_DIR/{}" \
      --preview-window=bottom:40%:border-rounded | \
  xargs -I {} hx "$CONFIG_DIR/{}"
